[package]
name = "keyutils"
version = "0.0.1"
authors = ["Ben Boeckel <mathstuf@gmail.com>"]
license = "BSD"
description = """
Rust interface to the Linux keyring.
"""

[dependencies]
bitflags = "~0.3.2"
libc = "~0.2.2"
