[package]
name = "keyutils"
version = "0.1.0"
authors = ["Ben Boeckel <mathstuf@gmail.com>"]
license = "BSD-3-Clause"
description = """
Rust interface to the Linux keyring.
"""

[dependencies]
bitflags = "~0.3.2"
errno = "~0.1.4"
libc = "~0.2.2"
